export const INDICATOR_CONFIG = {
  IMQ: {
    key: 'imq',
    title: 'Urban Data Explorer',
    subtitle: 'Indice de Mutation de Quartier · Paris',
    legendTitle: 'Indice de mutation',
    scoreField: 'score_imq_100',
    labelField: 'interpretation',
    scoreLabel: 'Score IMQ',
    statsMedianKey: 'score_imq_median',
    labels: ['Stable', 'Mutation modérée', 'Mutation forte'],
    statsPath: '/imq/stats',
    geojsonPath: '/imq/geojson',
    ruesPath: '/imq/geojson',
    mapType: 'polygon',
  },
  ITR: {
    key: 'itr',
    title: 'Urban Data Explorer',
    subtitle: 'Indice de Tension Résidentielle · Paris',
    legendTitle: 'Tension résidentielle',
    scoreField: 'itr_score',
    labelField: 'itr_label',
    scoreLabel: 'Score ITR',
    statsMedianKey: 'itr_score_median',
    labels: ['Très accessible', 'Accessible', 'Modéré', 'Tendu', 'Très tendu'],
    statsPath: '/itr/stats',
    geojsonPath: '/itr/geojson',
    ruesPath: '/itr/rues',
    mapType: 'circle',
  },
  SVP: {
    key: 'svp',
    title: 'Urban Data Explorer',
    subtitle: 'Score de Verdure et Proximité · Paris',
    legendTitle: 'Verdure et proximité',
    scoreField: 'svp_score',
    labelField: 'svp_label',
    scoreLabel: 'Score SVP',
    statsMedianKey: 'svp_score_median',
    labels: ['Très faible', 'Faible', 'Modéré', 'Bon', 'Excellent'],
    statsPath: '/svp/stats',
    geojsonPath: '/svp/geojson',
    ruesPath: '/svp/rues',
    mapType: 'circle',
  },
  IAML: {
    key: 'iaml',
    title: 'Urban Data Explorer',
    subtitle: "Indice d'Accessibilité Multimodale au Logement · Paris",
    legendTitle: 'Accessibilité multimodale',
    scoreField: 'iaml_score',
    labelField: 'iaml_label',
    scoreLabel: 'Score IAML',
    statsMedianKey: 'iaml_score_median',
    labels: ['Très accessible', 'Accessible', 'Modéré', 'Tendu', 'Très tendu'],
    statsPath: '/iaml/stats',
    geojsonPath: '/iaml/geojson',
    ruesPath: '/iaml/rues',
    mapType: 'circle',
  },
}

export function getIndicatorConfig(indicator = 'IMQ') {
  const key = (indicator || 'IMQ').toUpperCase()
  return INDICATOR_CONFIG[key] || INDICATOR_CONFIG.IMQ
}
